### ISSUE TITLE
Polymorphic effect aliases

### ISSUE THREAD

**Issue by jackfirth** [effekt-lang/effekt#112]
I'd like to write this:

```
effect Iterate[A] {def emit(element: A): Unit}
effect Reduce[A] {def consume(): Option[A]}
effect Transduce[A, B] = {Reduce[A], Iterate[B]}
```

But I get a parse error pointing at the `=` in `Transduce[A, B] = {...}` saying `'{' expected but '=' found`. Is this intentional? It looks more like a parsing oversight than an actual limitation.

**Comment by b-studios** [comment]
In deed, when working on the new effect tracking mechanism for closures, I temporarily dropped polymorphic effect aliases. They "just" need to be added back, there is no theoretical reason for not having them.

Sorry if this is inconvenient at the moment.
