### ISSUE TITLE
Run backend specific tests

### ISSUE THREAD

**Issue by b-studios** [effekt-lang/effekt#127]
We should rearrange tests to make it easier for newcomers to the project to only run the tests they are interested in.

## Context
After having merged the WIP LLVM Backend, we now have three different platforms and corresponding tests.

If we run `test` then all of the tests will be executed. This requires

- `node` for running the JS tests
- `scheme` for running the chez tests
- `opt-12` etc. for running the LLVM tests

There are also some unit tests which are independent of the backend (hopefully more in the future).
Frontend testing (including `neg` tests) are performed in the context of the (still main) JS backend.

**Comment by JonathanStarup** [comment]
I'm using `testOnly *MLTests` to only run the tests of my own file `effekt/jvm/src/test/scala/effekt/MLTests.scala`. I think it accepts regex to match files on

**Comment by b-studios** [comment]
Thanks! I also started using `testOnly ... -- GLOB` recently and it works really well. Reorganizing the tests a bit could help nevertheless :)
