### ISSUE TITLE
Why can't I find a hello world example

### ISSUE THREAD

**Issue by atlx** [effekt-lang/effekt#150]
Looked on the introduction page, examples, examples github directory, nothing.

Why is there no hello world example? :cry:

**Comment by marzipankaiser** [comment]
I don't know why there isn't one (probably, nobody thought of adding one), but here is a hello world, for now:
```effekt
def main() = {
    println("Hello World!")
}
```

(Actually, there is one in `examples/llvm/hello-world.effekt`, but that file name causes problems with some backends, see https://github.com/effekt-lang/effekt/issues/149)

**Comment by b-studios** [comment]
Probably, it would be good to start the (largely unmaintained) [intro](https://effekt-lang.org/docs/) with a hello world.

**Comment by marzipankaiser** [comment]
(Ah, there is another well-hidden one at https://effekt-lang.org/docs/getting-started#recommended-workflow)

**Comment by b-studios** [comment]
Addressed in effekt-lang/effekt-website#25.
