### ISSUE TITLE
Missing identifier sanitisation

### ISSUE THREAD

**Issue by jiribenes** [effekt-lang/effekt#159]
Upon defining a function with a parameter called `default`, the JavaScript backend returns an internal error, because `default` is a keyword in JavaScript:

<img width="902" alt="Screenshot 2022-09-27 at 13 59 32" src="https://user-images.githubusercontent.com/11269173/192519661-0d88ec2a-4417-47c8-8bda-8e69f1aca57a.png">

This probably stems from missing identifier sanitisation -- ideally, we should rename identifiers that clash with the backend's keywords.

Kinda related to #149.

**Comment by jiribenes** [comment]
The above case was an accident, this case is just me trying to break things on purpose:

<img width="595" alt="Screenshot 2022-09-27 at 14 13 37" src="https://user-images.githubusercontent.com/11269173/192523578-776dffe5-2edd-4314-a136-c4d4730e59c4.png">

**Comment by b-studios** [comment]
Commit 471f9da addresses both (though we should probably also use `$main` as the name for `main` in the REPL to avoid name clashes there.
