### ISSUE TITLE
Update the effect separator syntax to bring it into the 21st century

### ISSUE THREAD

**Issue by magnus-madsen** [effekt-lang/effekt#182]
Eff currently uses the forward slash `/` to separate types and effects. However, modern programming languages, with effect systems, have long established that `\` is a superior choice to `/` [1]. While such a design choice was reasonable in the past century, we believe that its time to bring Eff into the future!

We propose that Eff adopts `\` over `/` immediately.

Changing `/` to `\` has many benefits:

- No longer will programmers mistakenly believe you can divide a type by an effect.
- Danish programmers will have a harder time writing `\` hence will be appropriately encouraged to write more functional code.
- `\` has a higher ASCII number than `/` showing that it is indeed the greater choice.
- Let `T \/ E = Either[T, E]`, now which is clearer? (1) `U -> U \/ V -> U \ W` or (2) `U -> U \/ V -> U / W`. I think the code speaks for itself. 

[1] - It is of course redundant to state that modern programming languages come with an effect system.

**Comment by b-studios** [comment]
You know that you could've waited for April 1st, right?

**Comment by b-studios** [comment]
More honestly, I would like to change it. It is mostly backwards compat with papers, that's holding me back. 
However, I would *never* go to backslash.

1. Users in Germany don't know how to type backslash, because it is hidden on the keyboard (https://discussions.apple.com/thread/3174275)
2. I suddenly dislike operators (hence we introduced `sigma at {}` for boxes)

**Comment by paulbutcher** [comment]
Wait: the Danish keyboard has no `\`? How does anyone in Denmark use Windows? Or regular expressions? Or...? 😱

**Comment by magnus-madsen** [comment]
> Wait: the Danish keyboard has no `\`? How does anyone in Denmark use Windows? Or regular expressions? Or...? 😱

My keyboard has a key with three symbols on it: <>\. Presumably some kind of ctrl, alt, win, and/or alt gr gets me the backslash.

**Comment by magnus-madsen** [comment]
> ```scala
> def foo() using Exception: Unit = ...
> ```

Does Scala 3 use `using` for something? Type classes?

**Comment by b-studios** [comment]
Yes, which is related.

**Comment by magnus-madsen** [comment]
@b-studios Can we please have:

```scala
def getItDone(className: String, illegalThingToDo: String) abusing ClassNotFoundException: Unit = ...
```

to signal programmer intent.

**Comment by b-studios** [comment]
> My keyboard has a key with three symbols on it

Maybe you can bring your keyword into the 21st century and buy a new one ;)

![keyboard](https://user-images.githubusercontent.com/408265/200610011-080523ca-805d-4fad-9878-25201744456c.jpg)

Please no comments about how dirty my keyboard is.

**Comment by magnus-madsen** [comment]
But that's the backslash, just above enter!

**Comment by b-studios** [comment]
Due to inactivity of the assignee @magnus-madsen I close this ticket, for now.

**Comment by magnus-madsen** [comment]
We are happy to report that programmers coming from Effekt to Flix will now find that Flix has a specific error message (and quickfix) when one sloppily uses `/` to separate a type and effect. (Instead of the superior choice of `\`). 

https://github.com/flix/flix/pull/12414

This is exactly the type of cross-pollination of research ideas we have always been talking about!

**Comment by b-studios** [comment]
Couldn't the error message say: "This is Flix and not Effekt!"?
