### ISSUE TITLE
Opaque pointers in LLVM backend

### ISSUE THREAD

**Issue by serkm** [effekt-lang/effekt#195]
The LLVM backend should be updated to use [opaque pointers](https://llvm.org/docs/OpaquePointers.html).
However, an implementation would depend on [LLVM 15](https://llvm.org/docs/OpaquePointers.html#version-support) which is fairly recent and not yet updated on most linux distributions, so we might want to wait with this for now.

**Comment by b-studios** [comment]
We do not have many users :) If it works for all of our contributors -- mostly @phischu, @marzipankaiser, @jiribenes, @JonathanStarup, you and me (and the CI) it is fine to go ahead. All other contributors could disable the LLVM tests locally, I guess.

**Comment by b-studios** [comment]
Brew only goes up to version 14, if I am not mistaken. So maybe you can prepare it and we wait for brew and the linux distributions?

**Comment by b-studios** [comment]
Oh wait, no... 

https://formulae.brew.sh/formula/llvm

> Also known as: llvm@15

**Comment by jiribenes** [comment]
https://github.com/effekt-lang/effekt/blob/3aaa33b74f8b39085d46ee8c0bb5b59d65224461/effekt/jvm/src/main/scala/effekt/EffektConfig.scala#L51

I've noticed that the "default" LLVM version in `EffektConfig` hasn't been updated to 15.
(This broke my build 😅)
