### ISSUE TITLE
Lexer doesn't recognise escaped double quotes in strings

### ISSUE THREAD

**Issue by jiribenes** [effekt-lang/effekt#202]
I was just trying to use double quotes in a string 😄 

<img width="690" alt="Screenshot 2022-12-01 at 11 04 18" src="https://user-images.githubusercontent.com/11269173/205024944-0a9c5a41-ee2a-4bd6-8bb6-5e9cd33debf8.png">

This is not only a VSCode issue, since the message originates in the compiler:
<img width="626" alt="Screenshot 2022-12-01 at 11 06 55" src="https://user-images.githubusercontent.com/11269173/205025206-95fac05d-8755-4c4b-8117-d7c493e2302b.png">

Here's the regex in question:
https://github.com/effekt-lang/effekt/blob/18c94138ec3829b793095865c562d1ba74992994/effekt/shared/src/main/scala/effekt/Parser.scala#L208

**Comment by jiribenes** [comment]
Proposed regular expression:
```perl
\"(\\.|[^\"])*\"
```
- First, match `"`
- Then, zero or more times:
    - **EITHER** match `\` followed by _anything_
    - **OR** match something else than `"`
- Finally, match `"`

**Comment by b-studios** [comment]
I would be fine with merging this simple fix. Eventually, we should actually design strings and escape sequences at some point.
