### ISSUE TITLE
LLVM: crashes on `foldr`

### ISSUE THREAD

**Issue by marzipankaiser** [effekt-lang/effekt#207]
The following code:
```effekt
type ListInt {
    Nil(); Cons(hd: Int, tl: ListInt)
}

def foldr(l: ListInt, init: Int){ f: (Int, Int) => Int }: Int = {
    l match {
        case Nil() => init
        case Cons(hd, tl) => f(hd, foldr(tl, init){f})
    }
}

def main() = {
   val lst = [1,2,3,4,5,6,7,8,9,10]
   val sum = foldr(lst, 0){ (x,y) => x + y}
   println(sum)
}
```
([source code](https://gist.github.com/marzipankaiser/d083bd6df71818354a05d6b6abddb4b4))
causes the LLVM backend to crash with the following error:
```
opt: ./out/issue_b.ll:1112:20: error: '%init_102' defined with type '%Neg = type { ptr, ptr }' but expected 'i64'
        store %Int %init_102, ptr %init_102p.120
                   ^
[error] java.lang.RuntimeException: Nonzero exit value: 1
```
[stack trace omitted]

**Comment by marzipankaiser** [comment]
It seems that this was introduced by 7efb4649e079640461fdca02bf42eb944e25c09a.

**Comment by marzipankaiser** [comment]
[This](https://github.com/effekt-lang/effekt/commit/7efb4649e079640461fdca02bf42eb944e25c09a#diff-2bc35700065c09eb82c800736c2625a2516ddb669bb20acbfce3d9af8dbca683R65-R67) seems weird. `id` is bound by the `case` in the call to collect, not by the definition. So `tpe` does not correspond to `id`.

**Comment by b-studios** [comment]
It was already strange that

https://github.com/effekt-lang/effekt/commit/7efb4649e079640461fdca02bf42eb944e25c09a#diff-2bc35700065c09eb82c800736c2625a2516ddb669bb20acbfce3d9af8dbca683L65

extracts a valuetype, while the others extract a blocktype in the old code.

**Comment by b-studios** [comment]
You are completely right. The linked commit is wrong. The two things don't match up and I was introducing the bug there.

**Comment by b-studios** [comment]
Sadly we cannot be sure anymore that all symbols have annotated types (since I purposefully broke this invariant by refactoring core to typed core). Maybe we can 

1. type annotate variables in lifted (like in typed core)
2. copy over the types from core to lifted on these variables
3. free variables then collects type annotated variables

?
