### ISSUE TITLE
`lifted.Tree.freeVariables` distinguishes Variables by type

### ISSUE THREAD

**Issue by marzipankaiser** [effekt-lang/effekt#225]
The function `freeVariables` distinguishes Variables that have the same symbol but different type:
https://github.com/effekt-lang/effekt/blob/8365cbd7f24cd1a59f7c9b5a7a21a1c4dc2c7826/effekt/shared/src/main/scala/effekt/lifted/Tree.scala#L112-L177

This is a problem:
1. When types are syntactically different (e.g. alpha-equivalence, capabilities changing along the enclosing scopes)
   - If we want to prevent this, we'd have to rewrite the types in appropriate positions
2. When types are computed incorrectly

**Comment by marzipankaiser** [comment]
2 occurs in `PolymorphismBoxing` e.g. in the following program:
```effekt
effect Increment {
  def increment(): Unit
}
def main() = {
  try {

    def step(): Int = {
        def looper(): Int / Increment = 0
        looper()
    }

    step()
  } with Increment {
      def increment() = resume(())
  }
}
```
because the types in argument position `BlockVar`s are not transformed correctly.

**Comment by b-studios** [comment]
Yes, we should fix both, then.
