### ISSUE TITLE
Machine breaks if block within Member isn't a BlockVar

### ISSUE THREAD

**Issue by fritzladwig** [effekt-lang/effekt#238]
Inlining may replace BlockVars within Members, which breaks the code.

**Comment by fritzladwig** [comment]
LLVMTests.examples/llvm/obj.effekt
	Unsupported statement:
	App(
		Member(
			New(Implementation(
					Obj,
					List(
						Operation(
							foo,
							BlockLit(
								List(EvidenceParam(ev77904), ValueParam(x,Data(Int,List()))),
								Return(
									PureApp(
										BlockVar(infixAdd$1,Function(List(),List(),List(Data(Int,List()), Data(Int,List())),List(),Data(Int,List()))),List(),List(ValueVar(x,Data(Int,List())), Literal(40,Data(Int,List())))))))))),
			foo),
		List(),List(Evidence(List()), Literal(2,Data(Int,List()))))

**Comment by b-studios** [comment]
`examples/llvm/obj.effekt` is passing so maybe this is fixed? I am closing it for now.
