### ISSUE TITLE
Artifact for PLDI 2022

### ISSUE THREAD

**Issue by hflsmax** [effekt-lang/effekt#242]
Hi, I'm a graduate student and would like to test out the CPS translation presented in “A Typed Continuation-Passing Translation for Lexical Effect Handlers”.

Does this repository contain relevant artifact? If so, what commit should I use to test it out?

**Comment by hflsmax** [comment]
Thanks for your detail answer! Which backend do you think produces the fastest binary?

**Comment by b-studios** [comment]
> Which backend do you think produces the fastest binary?

Difficult to say, both the LLVM backend as well as the MLton backend are quite fast. However, both are still under development and only cover a subset of the language. What examples are you planning to play around with? Any idea already? Maybe we can help with it?

**Comment by hflsmax** [comment]
I'm having problem getting the master branch built. After running `sbt update`, `sbt install` gives these error. Sorry I've not work with Scala before and don't know how to resolve these dependency issues. Any pointers?

[compile_error.txt](https://github.com/effekt-lang/effekt/files/10946728/compile_error.txt)

**Comment by b-studios** [comment]
No worries, that is normal. Have you seen this guide? 

https://effekt-lang.org/contributing.html

It seems the git submodules are not cloned. So maybe run
```
git submodule init
git submodule update
```
?

**Comment by hflsmax** [comment]
Thanks. I'm trying to run `benchmark/triples.effekt` as a first step. I tried different backends. 

Both ml and chez-lift works.

For js, I'm not sure how to run the produced js code. Executing `node out/triples.js` doesn't really run the program. Any advice?

For LLVM, I encountered this error.
```
effekt.sh -c triples.effekt --backend llvm
[error] triples.effekt:1:1: Cannot find source for io/args
import io/args
^^^^^^^^^^^^^^
```

**Comment by b-studios** [comment]
Hey, sorry for the late reply. The JS backend goes into a monad and so you need to load the file and then call `run` on `main`:

```
node --eval "require('./FIEL.js').main().run()"
```

(also in this file it can be seen how each backend runs a program: https://github.com/effekt-lang/effekt/blob/master/effekt/jvm/src/main/scala/effekt/Runner.scala#L96)

For LLVM, I thought we had ported the io/args dependencies; however, it looks like it is still sitting in #223. @marzipankaiser can we just merge the PR?

**Comment by b-studios** [comment]
Sorry for the inconvenience @hflsmax , you could either locally merge the branch #223, copy file `args.effekt` (https://github.com/effekt-lang/effekt/pull/223/files#diff-ecb82a5b964a07ae0f30994a91f0f16a0eede8ea3f824761815597116af91135) or drop the import and hard code the parameters.

We will look into merging the branch ASAP on our side, to avoid this in the future.

**Comment by hflsmax** [comment]
Thanks. Just let you know that the branch can't be built out of the box and have merge conflicts with the master branch. 

I'm closing this issue now as my initial questions are addressed. Thanks again.

**Comment by b-studios** [comment]
You're welcome. @marzipankaiser we should look into merging the PR #223 soonish, regardless. 

@hflsmax just let us know if there is anything else.
