### ISSUE TITLE
Interface Polymorphic typing

### ISSUE THREAD

**Issue by matthias-dunkel** [effekt-lang/effekt#251]
# Code to reproduce
```
interface Data {
    def get[E](): E
}

def dataGenerator(string: String): Data at {}= {
    if(string == "Int") {
        new Data{
            def get[Int]() = 0 // Expected Int but got Int
        }
        
    } else {
        new Data {
            def get[Unit]() = () // Expected Unit but got Unit
        }
    }
}
```
# Problem
Defining the `get` function leads to the weird compile error: `Expected Int but got Int` and `Expected Unit but got Unit`. 

Typing the interface not like this is important: 
```
interface Data[E] {
    def get(): E
}
```

**Comment by b-studios** [comment]
Thanks for reporting. This sounds like a surprising bug in typer. Objects (as opposed to handlers) are not yet stress tested, so that's helpful.

**Comment by matthias-dunkel** [comment]
Sure. Where are the tests in the source code?

**Comment by b-studios** [comment]
https://github.com/effekt-lang/effekt/tree/master/examples/pos

**Comment by phischu** [comment]
This is expected behavior. In `def get[E](): E` the `E` is universally quantified. In `def get[Int]() = 0` the `Int` is a binding occurence for a fresh type variable with name `Int`. You want existentials but we don't have them yet.

**Comment by matthias-dunkel** [comment]
The error message should be something like "Existential Types not supported". I would suggest closing this issue by implementing the new error message or implementing existential types. But, I do not think, that I have the needed knowledge about the language or about existential types to implement them. I will use
>  `def get[A]() = unsafeCast[Int, A](0)` and hope for the best.

**Comment by b-studios** [comment]
There is a simple misunderstanding here. In the following code `Int` is a binding occurrence. That is, you name the type parameter `Int` (could as well be called `MyTypeParam`, or `A`). 

```
new Data{
  def get[Int]() = 0 // Expected Int but got Int
}
```
The message could  be a bit clearer (like `Expected type parameter Int, but got effekt.Int`) but I am closing this for now.
