### ISSUE TITLE
Importing resources is not possible

### ISSUE THREAD

**Issue by matthias-dunkel** [effekt-lang/effekt#270]
### Steps to reproduce
Create two files. 
1. resources.effekt:
```
extern interface R
extern resource r: R
```
2. main.effekt:
```
import FOLDER_PATH/resources

extern { r } def doNothing(): Unit = "" 
```
### Expected Output
Should run without any error message

### Actual Output
Error message: `Cannot resolve capture r`

It should be possible to import resources and interfaces.

**Comment by b-studios** [comment]
Thanks for the report. This sounds like a bug in Namer. Modules currently only export terms and types:

https://github.com/effekt-lang/effekt/blob/master/effekt/shared/src/main/scala/effekt/symbols/symbols.scala#L70-L80

The scope also has "resources" or captures:

https://github.com/effekt-lang/effekt/blob/master/effekt/shared/src/main/scala/effekt/symbols/Scope.scala#L178

But they are not imported:

https://github.com/effekt-lang/effekt/blob/master/effekt/shared/src/main/scala/effekt/Namer.scala#L47
