### ISSUE TITLE
Handling of type parameters for effects

### ISSUE THREAD

**Issue by marzipankaiser** [effekt-lang/effekt#281]
If we declare an effect with type parameters, e.g.
```effekt
effect Eff[A] {
  def use(): A
}
```

Then the number of type parameters is not checked at the usage site, so all of those compile:
```effekt
def foo(): Int / Eff = <>
def foo2(): Int / Eff[Int, Unit] = <>
```

Only if we ever use `do use`, it will complain that `Eff[Int]` is not allowed in that context, or that the number of type parameters does not match up *for the use call*. 
EDIT: If we ever try to define a handler with `try ... with ...`, then we get the appropriate error message there.

**Comment by b-studios** [comment]
Really??? I would have assumed that the kind checker would catch this

**Comment by marzipankaiser** [comment]
I would have assumed so, too, but apparently not:
<img width="823" alt="Screenshot 2023-09-01 at 10 33 34" src="https://github.com/effekt-lang/effekt/assets/2551444/cd11ec0d-c7f9-466c-94d3-196c32bfd8af">

**Comment by marzipankaiser** [comment]
Ah, interesting: At the `try ... with ...`, this check is made (we get a `Interface ... expects ... parameters, but ...`)

**Comment by b-studios** [comment]
We could add a pretyper phase (at one point we had it) to establish wellformedness _before_ typing. There is `Wellformedness` but it only runs after typer.
