### ISSUE TITLE
initialize array with default values

### ISSUE THREAD

**Issue by IR0NSIGHT** [effekt-lang/effekt#291]
feature request:
initialize mutable array of size with default values.
at the moment: `emptyArray[Int](5)` creates `( , , , , ,)` of unknown type, in js probably null
requested behaviour: `newArray[T](length, defaultValue)`
 `newArray[Int](5,0)` creates: `(0,0,0,0,0)`

**Comment by phischu** [comment]
I think it would be convenient to have

```
def initialize[T](size: Int) { index: Int => T }: Array[T]
```

For the more theoretically minded, we should have the following laws:

```
a = initiliaze(a.size) { i => a.index(i) }
initialize(n){f}.size = n
initialize(n){f}.index(i) = if i.inBounds(0, n) then f(i) else do IndexOutOfBounds()
```
