### ISSUE TITLE
Make effekt have a non-0 exit code when compilation fails

### ISSUE THREAD

**Issue by marzipankaiser** [effekt-lang/effekt#293]
When using `effekt ... --compile` to compile a program, the exit code is always 0, even when there is an error.
This makes writing scripts (shell scripts, build/test scripts etc) using it harder.

Example:
<img width="932" alt="Screenshot 2023-10-17 at 14 30 50" src="https://github.com/effekt-lang/effekt/assets/2551444/430b17d6-c104-4c74-bdbb-554bcf599cdf">

Intended output:
Terminate with exit code non-0 (e.g. 1), if there are errors.

**Comment by b-studios** [comment]
Fixed by #338
