### ISSUE TITLE
Unresolvable import nameclashes/named imports

### ISSUE THREAD

**Issue by IR0NSIGHT** [effekt-lang/effekt#299]
# Observed behaviour:
WHEN i import two modules foo and bar that both define ex()
THEN i can only access foo.ex() but not bar.ex() (whatever was imported first)

# Proposed expected behaviour:
WHEN i import two modules foo and bar that both define ex()
THEN both modules are imported but the defined functions dont invade the current top level scope/namespace
import foo
import bar
foo.ex()
bar.ex()

star imports are considered a codesmell (by me) because they frequently cause nameclashes and ambiguity that lead to bugs.
star imports should not be the default behaviour imo, but (if at all allowed) one that has to be explicitly called.
### The main problem right now is that i can not easily resolve name clashes

**Comment by jiribenes** [comment]
Related to current (lack of) namespacing / module system: #266 #264.

**Comment by b-studios** [comment]
Thanks for reporting, this is known and as @jiribenes says related to missing a proper implementation of namespacing. Since we need to deal with all of the related issues at once, I am closing this issue here.
