### ISSUE TITLE
Flag for outputting IRs

### ISSUE THREAD

**Issue by mm0821** [effekt-lang/effekt#303]
Following the recently merged (#294) flags `--build` and `--compile`, I would really appreciate having a compiler flag for outputting the generated intermediate representations (as is done [here on the website](https://effekt-lang.org/docs/implementation/lift-inference)).

**Comment by b-studios** [comment]
What do you typically use this for and why does the vscode plugin / lsp not suffice?

**Comment by mm0821** [comment]
I personally typically use this for examination of the evidence inferred by the compiler (e.g. to see whether things are implemented correctly or whether there is potential for optimization), but I think it is generally interesting to be able to inspect IRs for any compiler, i.p. for people developing compilers themselves to see how other compilers work internally.

I do not use vscode and I generally dislike the idea of having a feature like that tied to a specific editor, because I deem this a feature of the compiler itself. Language server support might be an option, but I do not really know how I can implement this e.g. for vim (what kind of request do I have to make?), so that still hinges on having language-server support for Effekt with this feature implemented in the editor used.

On the other hand, if it is a lot of work, it might not be worth it, as the audience appreciating this might be too small.

**Comment by b-studios** [comment]
It shouldn't be too hard since the functionality is already there for VSCode...

https://github.com/effekt-lang/effekt/blob/cf3b7d1fa7eda3a92f74351d99fcd3de159c900f/effekt/jvm/src/main/scala/effekt/Server.scala#L41-L84

**Comment by b-studios** [comment]
Maybe that could be a good starter issue for @marvinborner ? What do you think?

**Comment by mm0821** [comment]
Yes, sounds like a good issue to get to know the structure of the compiler.

Concerning the name of the flag, I like `showIR` as in the vscode plugin. Maybe the compiler could then be called with something like `effekt --showIR=core foo.effekt` for the`core` IR and similarly for `lifted` and potential others.

**Comment by b-studios** [comment]
Should it be shown it written to a file?

**Comment by mm0821** [comment]
I think writing to stdout is fine as long as no other things, e.g. warnings (which I think should rather be written to stderr btw.), are written there. Then one can pipe the stdout to a file if desired.

**Comment by marzipankaiser** [comment]
IMHO outputting to a file might be better. 🤔 Then, we could also support outputting multiple IRs in a more useful way (which can be helpful since, e.g., IIRC some symbol names change between compilation runs).
However, this can also be extended/changed in a later issue.

**Comment by mm0821** [comment]
You mean something like outputting different IRs to different files along with some additional information? That indeed sounds a bit more complicated and might be worth its own issue.

**Comment by b-studios** [comment]
I think it is not very difficult (I would guess 20-30 lines of code for everything). For the VSCode extension, I already generate separate files with file pseudo file extensions like

![image](https://github.com/effekt-lang/effekt/assets/408265/eb9992b4-65fd-4551-9f10-3e4baa559026)

The VSCode extension even syntax highlights them :)

**Comment by mm0821** [comment]
But I guess there is no additional information (like how symbol names have changed, or something), or is there?

So, there could either be a switch `--showIRs` outputting the different IRs into different files or a switch `--showIR=` which outputs a specified IR either into a file or to stdout (writing to stdout is probably a bit more unix-like). An advantage of the former option is that the user does not have to know the names of the IRs in advance. But of course that could be easily made available in `--help`, so I think either option (or even having both) is fine.
