### ISSUE TITLE
False error from linter when using Generics

### ISSUE THREAD

**Issue by IR0NSIGHT** [effekt-lang/effekt#304]
wierd linting error about generics, there is not real compiler error. File compiles and runs just fine
first appeared after rebasing on latest master, but can not guarantee that it wasnt there before.

![grafik](https://github.com/effekt-lang/effekt/assets/32139214/a964c31b-0de6-46e8-a30d-4aa8d46c3673)
    

See this commit:
commit adab23664be4cddcf3167130d45e660fe606bbfa (HEAD -> feature/init-array-default-values, origin/feature/init-array-default-values)
Author: IR0NSIGHT <irnsght@googlemail.com>
Date:   Wed Nov 8 11:43:30 2023 +0100

    format fix

And this file:
examples/pos/arrays.effekt

**Comment by b-studios** [comment]
Thanks for your report. Can you please provide the minimized example as code in the issue (using code fences "```")?

Also, it is not a linter, but an error reported by our type checker

**Comment by IR0NSIGHT** [comment]
issue is resolved, i had a messed up master branch which i rebased my featurebranch on.
I cant tell exactly why it would run correctly and still show as faulty, but the error instance itself is now resolved when using the correct master.
