### ISSUE TITLE
loop with early return

### ISSUE THREAD

**Issue by IR0NSIGHT** [effekt-lang/effekt#314]
Feature request:
a for loop with ability to return early/break

Right now there is no such feature (afaik): 
each(n,m) executes from start to finish, no option to break early.

In order to use a return early functionality (as is dictated in my case by the existing are-we-fast-yet benchmarks) i have to fall back to "while (run)" ... and mutate run in the loop:
```
var run = true
while (run) {
   if (...) { run = false}
}
```
This is much harder to read/understand/verify and invites bugs (mutable state and unnecessary while loop)

so: 
each() with break (and continue) would be nice to have.
(any kind of early return would suffice, it doesnt have to be "break")

**Comment by jiribenes** [comment]
Thanks for the issue!
I'm putting some additional context below:

### Existing related work

The ML backend has a `Control` effect:
https://github.com/effekt-lang/effekt/blob/11218d9888a072350e1c5bd5318d7f97f5783b35/libraries/ml/effekt.effekt#L214-L217

and a function `each` that allows one to use the `Control` effect and handles it correctly:
https://github.com/effekt-lang/effekt/blob/11218d9888a072350e1c5bd5318d7f97f5783b35/libraries/ml/effekt.effekt#L230

I don't know if we want to port this version of `each` to the JavaScript backend as well 🤔 

#### Examples
https://github.com/effekt-lang/effekt/blob/11218d9888a072350e1c5bd5318d7f97f5783b35/examples/ml/lib/loops.effekt#L1-L17
