### ISSUE TITLE
Compiler crash on extra pattern arguments

### ISSUE THREAD

**Issue by jiribenes** [effekt-lang/effekt#328]
The following (minimised) code example:
```scala
type Result {
  Failure()
}

def main() = {
  val r = Failure()
  r match {
    case Failure(msg) => println(msg)
  }
}
```

produces a compiler crash with:
```
Exception in thread "main" PlainTextError(Cannot find value binder for msg,Some(Range(Position(8,34,FileSource(repro.effekt,UTF-8)),Position(8,37,FileSource(repro.effekt,UTF-8)))),Error)
```
(where 8:34-8:37 point to the use of `msg`)

which comes from Annotations via Namer (i.e. before getting to Typer):
https://github.com/effekt-lang/effekt/blob/be63dbb804b362ea99d182d9b45a93fe51f549af/effekt/shared/src/main/scala/effekt/context/Annotations.scala#L445

However, if we don't use `msg` at all, like in:
```scala
type Result {
  Failure()
}

def main() = {
  val r = Failure()
  r match {
    case Failure(msg) => println("ohno")
  }
}
```
we get the correct error message:
```
[error] repro.effekt:8:10: Wrong number of pattern arguments, given 1, expected 0.
    case Failure(msg) => println("ohno")
```
which comes from Typer:
https://github.com/effekt-lang/effekt/blob/4d2e4868c99482d9c1fa327c7c542dc27e2c344f/effekt/shared/src/main/scala/effekt/Typer.scala#L510

**Comment by b-studios** [comment]
I'd start in Namer to search for the bug

**Comment by b-studios** [comment]
Actually, we need to abort not error on an arity mismatch. Otherwise the type will not be found later
