### ISSUE TITLE
println output should not be buffered during execution

### ISSUE THREAD

**Issue by IR0NSIGHT** [effekt-lang/effekt#336]
using panic("hello world") will swallow ALL other print statements of the execution, making debugging it impossible
having an infiinite loop or recursion will swallow ALL print statements, making debugging impossible

both issues are caused by console output not being directly passed to the console but being buffered (or something) until the execution finished.
with the absence of a stepper, println is my only way to debug other than "wir lösen das problem durch anstarren" :smile:

**Comment by b-studios** [comment]
I believe the problem is not the panic, but that the output of the `node` process is not _streamed_ to the JVM. If I were to debug this, I would start by looking here:

https://github.com/effekt-lang/effekt/blob/master/effekt/jvm/src/main/scala/effekt/Runner.scala#L70
