### ISSUE TITLE
Misleading error message when using parametric effects

### ISSUE THREAD

**Issue by jiribenes** [effekt-lang/effekt#352]
The following code:
```scala
effect Emit[A](x: A): Unit
def emit[A](x: A): Unit / Emit[A] = do Emit[A](x)
```

returns the error message:
```
Effect Emit is not allowed in this context.
```
pointing to the RHS of the second declaration:
<img width="732" alt="Screenshot 2023-12-19 at 11 58 01" src="https://github.com/effekt-lang/effekt/assets/11269173/3d5f5e80-fde6-44f1-a0de-7d311773f9f1">

---

The correctly to write the program is to not let the `Emit` in the return type take a type parameter:
```
effect Emit[A](x: A): Unit
def emit[A](x: A): Unit / Emit = do Emit[A](x)
```

It would therefore be nice to provide a better error message (and to report it in the return type where it stems from).

**Comment by b-studios** [comment]
Strangely this is not caught by our kind checker, but should.
