### ISSUE TITLE
Cannot escape double quotes in extern strings

### ISSUE THREAD

**Issue by jiribenes** [effekt-lang/effekt#353]
Minimal example:
```scala
extern pure def foo(): String = "\"this is a string\""
```
throws an error as `\"` is not allowed in extern strings:
<img width="852" alt="Screenshot 2023-12-19 at 12 13 22" src="https://github.com/effekt-lang/effekt/assets/11269173/8a3e0d7e-0c7d-4eeb-bc5b-a420b494aca9">

However, double quote escaping works in normal strings:
```scala
val foo = "\"this is my quoted string\"
```

I believe that my actual use case needs the double quotes in an extern string
because it's a separate parameter that I have to provide:
```scala
extern type ByteArray
extern pure def fromString(s: String): ByteArray = "(new TextEncoder().encode(s))"
extern pure def toString(b: ByteArray): String = "(new TextDecoder(\"utf-8\").decode(b))"
```

---

Related: #350, #202

**Comment by b-studios** [comment]
If this is for the JS backend you can use `"(new TextDecoder('utf-8').decode(b))"` as a workaround for now.

**Comment by jiribenes** [comment]
Another workaround is to use multiline strings:
```scala
extern pure def toString(b: Bytes): String = """
    (new TextDecoder("utf-8").decode(b))
"""
```
