### ISSUE TITLE
Make writing neg-tests easier and more robust

### ISSUE THREAD

**Issue by b-studios** [effekt-lang/effekt#375]
If I understand correctly, the Scala compiler uses the following strategy to specify neg-tests:

- either there is a check file with expected output
- or the source file has one or multiple annotations as comments

We could do similar:
```scala
def main() = {
   1 + "test" // ERROR
}
```

That is, we check whether there is an error, reported on that line.

This is more robust since it does not look into the message and a lot easier to specify then creating a separate `.check` file.

**Comment by b-studios** [comment]
Later, we could also support different kinds of comments that allow checking for more (e.g., is this a parse error, typer, etc.)

**Comment by jiribenes** [comment]
Related work is LLVM's `lit` tool: here's an example test: https://github.com/llvm/llvm-project/blob/main/clang/test/Lexer/header.cpp

**Comment by b-studios** [comment]
Closing for now. Of course we can keep discussing more advanced implementations :)
