### ISSUE TITLE
Multiline strings are not recognised

### ISSUE THREAD

**Issue by jiribenes** [effekt-lang/effekt#408]
Currently, it is impossible to write multiline strings (other than in extern definitions) -- I believe that's a regression.

<img width="474" alt="Screenshot 2024-03-06 at 11 05 26" src="https://github.com/effekt-lang/effekt/assets/11269173/b2ed6709-271f-403d-821b-c81a2af07efa">

**Comment by b-studios** [comment]
I am not sure whether we ever supported that, but I guess we could. 

At least in the last version it seems to be like today:

https://github.com/effekt-lang/effekt/blob/523e11bea6c862935c86e84f8660a4d88574b95d/effekt/shared/src/main/scala/effekt/Parser.scala#L733
