### ISSUE TITLE
Can another symbol be chose instead of /

### ISSUE THREAD

**Issue by sirinath** [effekt-lang/effekt#46]
Can another symbol be chose instead of `/`

**Comment by b-studios** [comment]
You mean for effect annotations? Yes, I have also been thinking about this. Sadly papers have already been written using this syntax... Is there anything you have in mind?

**Comment by sirinath** [comment]
Nothing particular

**Comment by b-studios** [comment]
I'll close this issue, but we will definetely keep it in mind...
