### ISSUE TITLE
Since the syntax is similar to Scala can it be contributed to Scala 3.+?

### ISSUE THREAD

**Issue by sirinath** [effekt-lang/effekt#47]
Can the work done here be directed so it can be added to a production language like Scala. It would be good to have it sooner than later hence can the research be adopted and contributed to Scala 3.+?

**Comment by b-studios** [comment]
This is a very good question and sorry for only responding now! Yes, the syntax is very similar, but the underlying language is still far away from Scala. We do not have subtyping, path-dependent types, or objects in Effekt. So there is still a lot of research left to be done :)

**Comment by sirinath** [comment]
I mean use the insight to contribute to effects implementation in Scala.

**Comment by b-studios** [comment]
Thanks for the suggestion. Indeed we are in close collaboration with the Scala team. I am closing this issue, since it is not directly actionable. But feel free to ask any questions :)
