### ISSUE TITLE
Inconsistent file names in output directory

### ISSUE THREAD

**Issue by marvinborner** [effekt-lang/effekt#471]
While working on automatic benchmarks I noticed that the names of generated files are not consistent for literate Effekt and normal Effekt files: Literate files include the full relative path while normal files don't.

Reproduction:

- `effekt.sh examples/benchmarks/nqueens.effekt` generates `out/nqueens` and `out/nqueens.js`
- `effekt.sh examples/features/adt.effekt.md` generates `out/examples_features_adt` and `out/examples_features_adt.js` (instead of expected `out/adt` and `out/adt.js`)

I'm not entirely sure which of the two naming schemes is better, but we should probably include the relative path in both cases.

**Comment by dvdvgt** [comment]
Fixed with #498
