### ISSUE TITLE
Runtime in typescript

### ISSUE THREAD

**Issue by oovm** [effekt-lang/effekt#48]
I tried to understand [effekt_runtime.js](https://github.com/effekt-lang/effekt/blob/master/lib/effekt_runtime.js) but encountered some difficulties.

Is there an implementation of typescript version?

**Comment by b-studios** [comment]
Thanks for trying to understand the runtime. It is (more or less) a translation from Scala to JavaScript. If you want to look at types, maybe this one helps you: https://github.com/b-studios/scala-effekt/tree/master/shared/src/main/scala/effekt

**Comment by oovm** [comment]
Thanks, thats enough!
