### ISSUE TITLE
About Effect Polymorphism

### ISSUE THREAD

**Issue by oovm** [effekt-lang/effekt#49]
I have some questions about the section [effect-polymorphism](https://effekt-lang.org/docs/concepts/effect-polymorphism).

```scala
def eachLine(file: File) { f: String => Unit / {} }: Unit / {}
```

Is this equivalent to a generic effect:

```scala
def eachLine[E](file: File) { f: String => Unit / E }: Unit / E
```

For example, I want to express that for any effect E, there must be an output.

Can it be expressed as:

```scala
def eachLine[E](file: File) { f: String => Unit / E }: Unit / { Console }
```

**Comment by b-studios** [comment]
Hey, sorry for the late response. Yes,

```
def eachLine(file: File) { f: String => Unit / {} }: Unit / {}
```
is indeed very similar to what you refer to as a generic effect `E`. In our paper, we call this form of effect polymorphism "parametric effect polymorphism", while the one supported by Effekt we call "contextual effect polymoprhism."


> For example, I want to express that for any effect E, there must be an output.

I don't fully understand your question. In Effekt you would simply write:

```
def eachLine(file: File) { f: String => Unit / {} }: Unit / { Console }
```
if eachLine is using `Console` itself.

**Comment by b-studios** [comment]
I am closing this for now, if you have questions don't hesitate to ask
