### ISSUE TITLE
Store string literals in their unescaped form

### ISSUE THREAD

**Issue by jiribenes** [effekt-lang/effekt#503]
## Motivation

Currently, we store string literals in an escaped form, for example as `"ab\nc\td"` instead of storing in the unescaped form `"ab<newline>c<tab>d"` where `<newline> = 0x0A`; `<tab> = 0x09`.
This works fine on the JavaScript backend, but breaks on the LLVM backend, as the string literals are unescaped "ab\nc" , but the ones we get from reading a file are escaped `"ab<newline>c"` :fire: (so `"ab\nc".split("\n")` works as expected, but `readFile(filename).split("\n")` does not)
See the following comment for more information: https://github.com/effekt-lang/effekt/issues/494#issuecomment-2156704601

## Potential solutions

There are two potential ways of fixing this:
1. In Lexer, upon creating a string token, we unescape it and keep it unescaped the whole time in the compiler, then escape them in codegen for the backends where we need to (e.g. JavaScript). [unimplemented]
2. Do the opposite, keep storing strings in the escaped form and only unescape in codegen, which was already preliminary implemented for Machine in a very nice way by @marvinborner here: https://github.com/effekt-lang/effekt/pull/497

Option **1.** is slightly more work, but allows us to then have custom escapes for Effekt itself (like `\u{1f4a9}` or whatever) which then can be translated to each backend, thus actually becoming backend-agnostic. The downside is that we then also need to escape the string when debug-printing it from the compiler.

---

In a discussion among the Effekt developers, we decided to do option **1.** after the new parser (#495) gets merged.
Feel free to take this issue on, I might not have the time for it.

**Comment by dvdvgt** [comment]
I propose we use `\u<DIGIT>+` for Unicode character literals and likewise `\u<DIGIT>+` inside strings, simply because then we can use `StringContext.processEscapes` for the latter and don't have to take care of it ourselves

**Comment by b-studios** [comment]
@jiribenes you had some opinion on the syntax of escapes, didn't you?

**Comment by jiribenes** [comment]
> I propose we use `\u<DIGIT>+` for Unicode character literals and likewise `\u<DIGIT>+` inside strings, simply because then we can use `StringContext.processEscapes` for the latter and don't have to take care of it ourselves

Sounds fine to me, at least as a first step, especially if we can reuse `StringContext.processEscapes` (at least for now, anyways).

Given time, we could actually do the super-correct solution of parsing/lexing the escapes ourselves and then storing the escaped version directly (so without any need to call `StringContext.processEscapes` at all), but I'd be very happy if we could postpone that for later in order to prioritise the merge of #495 :)

**Comment by jiribenes** [comment]
Resolved by #495, tested with repro from https://github.com/effekt-lang/effekt/issues/494#issuecomment-2156704601 👍
