### ISSUE TITLE
Overeager JS inliner forgets to parenthesize

### ISSUE THREAD

**Issue by jiribenes** [effekt-lang/effekt#505]
Continuing from https://github.com/effekt-lang/effekt/pull/493, we haven't solved the general issue: the JS inliner is great at inlining, but it might inline `(s1 + s2).length` into `s1 + s2.length` without the parentheses.

Here's an example from @marvinborner from #493 which showcases similar buggy behaviour:
```scala
> "abc" == "def"
false
> ("abc" == "def").not
false
> not ("abc" == "def")
false
> val huh = "abc" == "def"
> huh.not
true
```

**Comment by b-studios** [comment]
Inductively, it should be enough to always parenthesize the spliced expressions.
