### ISSUE TITLE
Consistently name generated ML binary

### ISSUE THREAD

**Issue by marzipankaiser** [effekt-lang/effekt#506]
Most backends generate an executable with the same name as the file containing the `main`.
This is not the case for ML, which always generates one named `mlton-main`:

https://github.com/effekt-lang/effekt/blob/1f0c055f69c0596098e7b135ddc0e408cb08efbb/effekt/jvm/src/main/scala/effekt/Runner.scala#L301-L304

We should change this to make it consistent with the other backends.

**Comment by jiribenes** [comment]
MLton was removed in #616
