### ISSUE TITLE
Move to a rolling release scheme

### ISSUE THREAD

**Issue by jiribenes** [effekt-lang/effekt#533]
### Motivation

We are way too slow to release new versions, but at the same time it's unnecessarily difficult to install Effekt for students and other users. Let's resolve that by moving to a weekly ("nightly") release.

### Details

On GitHub CI, set up a cronjob for every Monday at 3am to make a new release.

Version format: `M.YY.WW`, so for example `0.24.10` for the 10th week of 2024 where the major version is `0`.
A related commonly used format is called [Calendar Versioning](https://calver.org).

#### Possible problems

What if we want  to release a new (sub)version quickly?

Regarding prior art, Minecraft uses `YYwWWN` (where `N` is some unique identifier) for their weekly snapshots, so for example `24w10a`.
We could similarly do `0.24.10.0` or `0.24.10.a` or something like that. :)

**Comment by b-studios** [comment]
I'm fine with `M.YY.WW` and attaching a `.1` or something for quick fixes, if ever needed.
