### ISSUE TITLE
Variable with boxed function allows call of function without necessary captures in scope

### ISSUE THREAD

**Issue by dvdvgt** [effekt-lang/effekt#537]
Consider this program:

```
interface Greet { def sayHello(): Unit }

def main() = {
  var f = box { () }
  try { f = box { g.sayHello() } }
  with g: Greet { def sayHello() = println("hello!") }
  f()
}
```

This should of course fail at compile-time since at the call-site of `f`, the capture `g` is not in scope. However, it **fails** with the following error **at runtime**:

```
Prompt 2 not found
```

The type of `f` is inferred as `() => Unit at { g }`. Thus, the first assignment is also valid due to capture subtyping. If you actually try to annotate it like this, you cannot since `g` is not in scope (TIL this is called a Voldemort type according to @jiribenes)

If you instead annotate `f` with the type of its first assignment, the program expectedly fails at compile-time:

```
interface Greet { def sayHello(): Unit }

def main() = {
  var f: () => Unit at {} = box { () }
  try { f = box { g.sayHello() } }
  with g: Greet { def sayHello() = println("hello!") }
  f()
}
```

**Comment by b-studios** [comment]
Potentially fixed by #552
