### ISSUE TITLE
Recursive state cannot be annotated

### ISSUE THREAD

**Issue by b-studios** [effekt-lang/effekt#547]
The example below typechecks, but the type of `storage: Option[() => Unit at {storage, io}]` cannot be annotated since it does refer to `storage`.

```
interface Greet { def sayHello(): Unit }

def helloWorld() = {
 var storage = None();
 try {
   do sayHello()
 } with Greet {
   def sayHello() = { 
     storage = Some(fun() { resume(())});
     println("Hello!"); resume(()) 
   }
 }
}
```

Semantically, it makes sense to support this (and we do). However, we appear to have forgotten to also support it in Namer.

Thanks @e45lee for reporting!

**Comment by jiribenes** [comment]
For completeness, we usually work around this in existing Effekt code [(i.e. in the `scheduler` examples)](https://github.com/search?q=repo%3Aeffekt-lang%2Feffekt+yield+path%3Ascheduler.effekt+&type=code) with
```scala
def helloWorld = region this {
  var storage: Option[() => Unit at {this, io}] in this = None()
  //                                 ^^^^          ^^^^
  // ...
}
```

**Comment by b-studios** [comment]
Apparently this example also doesn't work in mlton, but I haven't reproduced the issue

**Comment by b-studios** [comment]
Duplicate of #282
