### ISSUE TITLE
What does `at {global}` mean?

### ISSUE THREAD

**Issue by mio-19** [effekt-lang/effekt#550]
https://github.com/effekt-lang/effekt/blob/754fa42989057d0db14f767253d12a0541a976f5/examples/benchmarks/are_we_fast_yet/bounce.effekt#L14
I found `at` and `{global}` in this file. I failed to find them in the document on the website.

**Comment by jiribenes** [comment]
Hi @mio-19, thanks for the question!

We haven't yet ported the tutorial from the [OOPSLA 2022 paper](https://dl.acm.org/doi/10.1145/3527320), but you can take a look at the interactive explanation in its artifact, it's valid Effekt code (modulo small syntactic differences):
https://se-tuebingen.github.io/oopsla-2022-artifact/casestudies/regions.html

What's missing there is that `global` is a, well, _global_ region you can't backtrack over. We therefore tend to use it to track global mutable state.

**Comment by b-studios** [comment]
Thanks for your question. We will try to explain it in #536 but I'll close the issue for now.
