### ISSUE TITLE
Effects need to be fully known

### ISSUE THREAD

**Issue by omentic** [effekt-lang/effekt#663]
I have hit the second half of the issue in #661 again (and figured I'd open a second issue since it was very unrelated to the original issue). This commented-out code fails to compile: https://gist.github.com/omentic/58b553920b4c8402b04c2873901291df#file-iter-scala-L464

It produces a very long "failed to typecheck overload" error, but it seems like the core issue is 
```
Possible overload: iter::take of type [T](Int){() => Unit / { Yield[T] }} => Unit / { Yield[T] }
  Effects need to be fully known: Yield[T]
```

I suppose this is probably another case needing a heuristic?

**Comment by b-studios** [comment]
Yes that's right. At `take` it is not possible to know which effect to handle.

While you probably mean `Int`, in general it could be anything. 

You can always annotate the type argument to work around it: `take[Int] { ... }`.

**Comment by omentic** [comment]
Ah - thanks a bunch! :smiley: 

```scala
[effekt]$ java -jar bin/effekt examples/iter.effekt 
hello!
Cons(3, Cons(2, Cons(1, Cons(1, Cons(0, Nil())))))
Cons(144, Cons(34, Cons(8, Cons(2, Cons(0, Nil())))))
```

**Comment by b-studios** [comment]
Since you work on streams you might be interested in #527. Maybe you have some insights that you would like to share?
