### ISSUE TITLE
Parse '\'' correctly

### ISSUE THREAD

**Issue by jiribenes** [effekt-lang/effekt#724]
Currently `'\''` doesn't ~~parse~~ _lex_, but it really should :)
See details below.

cc @b-studios

**Comment by jiribenes** [comment]
Here's where a `\'` escape would come in handy:
https://github.com/effekt-lang/effekt/blob/82af20f4f356f63df61cc7f610af5c37b5bc99d7/effekt/shared/src/main/scala/effekt/Lexer.scala#L433-L441

The only issue is: do we want to allow `\'` in a string `"string"` as opposed to writing it directly? Similarly, do we want to allow `\"` in a char `'c'" as opposed to writing it directly?
How does this look for other languages?

**Comment by marzipankaiser** [comment]
My opinion on the questions: I personally prefer it if both `\'` and `\"` are allowed in both `''` and `""`. This is because this allows me to copy-paste between the two, and I don't have to think about which kind of string I'm in.

**Comment by jiribenes** [comment]
Me too. 💯 
In that _case_, all that needs to be added is a `case` for `'\''` in the code linked above, I think. :)

**Comment by jiribenes** [comment]
You can still write that in any case, the only difference is if you can _also_ write `'\"'` and `"\'"`.

**Comment by b-studios** [comment]
Ok, great 👍 Thanks for the explanation.
