### ISSUE TITLE
Missing JavaScript Implementation for show Function on Byte Data Type

### ISSUE THREAD

**Issue by CanCodes** [effekt-lang/effekt#749]
Hi,

While working on a project, I noticed that the show function for the Byte data type does not have a JavaScript implementation. You can find the relevant code here:
https://github.com/effekt-lang/effekt/blob/eb662be391d19eda0194af32eb7362c49032bbb5/libraries/common/effekt.effekt#L87-L91

To address this, I’ve added the following line to my local build:
```diff
extern pure def show(value: Byte): String =
+  js "'' + ${value}"
  llvm """
    %z = call %Pos @c_bytearray_show_Byte(i8 ${value})
    ret %Pos %z
  """
```
If this solution is acceptable, I’d be happy to open a PR for the implementation. Let me know what you think!

**Comment by jiribenes** [comment]
Hey, looks good to me, feel free to create a PR. :)
